# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180214_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchExceptionID', models.IntegerField()),
                ('batchID', models.IntegerField()),
                ('createdBy', models.CharField(max_length=500)),
                ('createdOn', models.DateField()),
                ('modifiedBy', models.CharField(max_length=500)),
                ('modifiedOn', models.DateField()),
                ('fileName', models.CharField(max_length=500)),
                ('exceptionReason', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
